apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace | default .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.gateway.name }}
    app.kubernetes.io/part-of: {{ .Values.global.appName }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    - name: {{ .Values.gateway.listener.name }}
      protocol: HTTP
      port: {{ .Values.gateway.listener.port }}
      allowedRoutes:
        namespaces:
          from: Same
