apiVersion: v1
kind: ConfigMap
metadata:
  name: food-service-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: food-service
data:
  APP_NAME: "Food Logging Service"
  HOST: "0.0.0.0"
  PORT: "{{ .Values.foodService.port }}"
  CORS_ORIGINS: "{{ .Values.global.corsOrigins }}"
