apiVersion: v1
kind: ConfigMap
metadata:
  name: macro-service-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: macro-service
data:
  APP_NAME: "Macro Calculation Service"
  HOST: "0.0.0.0"
  PORT: "{{ .Values.macroService.port }}"
  FOOD_SERVICE_URL: "http://food-service:{{ .Values.foodService.port }}"
  AUTH_SERVICE_URL: "http://auth-service:{{ .Values.authService.port }}"
  CORS_ORIGINS: "{{ .Values.global.corsOrigins }}"
