apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app.kubernetes.io/part-of: nutritrack
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change-me-postgres-root-password
  AUTH_USER_PASSWORD: change-me-auth-db-password
  FOOD_USER_PASSWORD: change-me-food-db-password
  MACRO_USER_PASSWORD: change-me-macro-db-password
  COMPLIANCE_USER_PASSWORD: change-me-compliance-db-password
