apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app: frontend
